export declare const widthVar: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
export declare const heightVar: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
export declare const minHeightVar: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
export declare const modalOverlay: string;
export declare const modalContent: string;
export declare const closeButton: string;
export declare const modalHeader: string;
export declare const modalDescription: string;
export declare const modalFooter: string;
export declare const confirmModalContent: string;
