export declare const sizeVar: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
export declare const DefaultAvatarContainerStyle: string;
export declare const DefaultAvatarMiddleItemStyle: string;
export declare const DefaultAvatarMiddleItemWithAnimationStyle: string;
export declare const DefaultAvatarBottomItemStyle: string;
export declare const DefaultAvatarBottomItemWithAnimationStyle: string;
export declare const DefaultAvatarTopItemStyle: string;
export declare const avatarRoot: string;
export declare const avatarImage: string;
export declare const avatarFallback: string;
export declare const hoverWrapper: string;
export declare const removeButton: string;
